version: '2.4'

# This is NOT a production-like setup, this is for local setups only
services:
  # uses nginx variant, "just works". This sits in front of the two services
  # below. This supports wildcards and SLL
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    # Mounted to "docker socket" - reading information coming out of docker
    # engine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  # Without nginx proxy above, these would have to be published on their own
  # ports
  nginx:
    image: nginx
    environment:
      # "DNS name" = "virtual host", virtual hosting = concept of handling
      # multiple domains (or IPs) on same server
      - VIRTUAL_HOST=dude.localhost

  ghost:
    image: ghost
    environment:
      - VIRTUAL_HOST=ghost.localhost

